Algoritmo "Ex_3_A"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Os pares de instruções abaixo produzem o mesmo resultado?
// Autor(a)    : Camila Carla Soares
// Data atual  : 13/04/2022
Var
// Seção de Declarações das variáveis

A : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

A <- (4/2) + (2/4)
Escreval ("A: ",A)
A <- 4/2 + 2/4
Escreval ("A: ",A)
Escreval ("Produzem o mesmo resultado")

Fimalgoritmo